GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDYxNjYwMjAsImV4cCI6MTYwNjE2NjAzNSwiYXVkIjoiNWZiNTVhYmZhODExMGMzYjU0MzMwYmEwIiwiaXNzIjoicGlja3VwdXJwYWdlLmNvbSJ9.BfUXQZOr4mTGzV0J7iuQbRIl7wiIGOf0TU5er7YfqhI
###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "hendri11@abc.com",
    "password": "1234"
}
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "hendri4@abc.com",
    "password": "1234"
}

###

POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDY0MTEwNjIsImV4cCI6MTYwNjQxMTA5MiwiYXVkIjoiNWZiNTVhYmZhODExMGMzYjU0MzMwYmEwIiwiaXNzIjoicGlja3VwdXJwYWdlLmNvbSJ9.LJFeEyTUhbqelAHoQEaw57wiLLxZlFIAPYn_wey9Qr8"
}

###

DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDY1NDQ5NzQsImV4cCI6MTYzODEwMjU3NCwiYXVkIjoiNWZiNTVhYmZhODExMGMzYjU0MzMwYmEwIiwiaXNzIjoicGlja3VwdXJwYWdlLmNvbSJ9.KxbchnzKiEw7W-QVrOS3u86i9qsv2EVLFG-Q_vcQBvI"
}